#!/usr/bin/env bash
# Builds the demo tool and generates the key material and the API server's
# authentication configuration. Idempotent, and safe to rerun: the API server's
# key is bound to a date, so rerunning is how it gets refreshed.
#
# The directory layout is the trust boundary, not just filing:
#
#   fixtures/node/    bind mounted into the control plane container
#   fixtures/client/  host only, never mounted anywhere
#   fixtures/bin/     the demo tool
#
# Note what is not under node/. The ECDSA private key is not, because it never
# needs to be. Neither is the root HMAC secret: the server gets a key derived
# from it, bound to one UTC day, which is the whole point of the ladder. A shared
# secret normally means the verifier can forge signatures indistinguishable from
# the client's; here it can do so only for today, and only for this one key.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
node=fixtures/node
client=fixtures/client
bin=fixtures/bin
mkdir -p "$node" "$client" "$bin"

demo="$bin/httpsig-demo"
go build -o "$demo" ./cmd/httpsig-demo
echo "built $demo"

# kind.yaml owns the cluster name. It is also the value of the ladder's cluster
# scope step, so both the broker and the client have to agree on it, and reading
# it back from one file is cheaper than keeping three copies in step.
cluster="$(grep -oP '^name:\s*\K\S+' kind.yaml)"

# A demo secret in a repository is not a secret. It is named as such so that no
# one is tempted to lift the pattern into anything real.
readonly hmac_secret="httpsig-kind-demo-not-a-real-secret"

# Written with printf rather than echo so there is no trailing newline. Both
# sides trim one, but a secret that differs by a byte between them fails as a
# signature mismatch with nothing to point at.
printf '%s' "$hmac_secret" >"$client/hmac.secret"
chmod 600 "$client/hmac.secret"

if [[ ! -f "$client/ecdsa-p384.key" ]]; then
  # SEC1 "EC PRIVATE KEY" PEM, which the client parses directly. PKCS#8
  # ("PRIVATE KEY") also works if you would rather use openssl genpkey.
  openssl ecparam -name secp384r1 -genkey -noout -out "$client/ecdsa-p384.key"
  chmod 600 "$client/ecdsa-p384.key"
  echo "generated $client/ecdsa-p384.key"
fi
if [[ ! -f "$client/ecdsa-p384.tamper.key" ]]; then
  # An unrelated key on the same curve, for the negative test. Generated here
  # rather than in the plugin so the plugin has no reason to hold a key
  # generator, and so the same wrong key is used every run.
  openssl ecparam -name secp384r1 -genkey -noout -out "$client/ecdsa-p384.tamper.key"
  chmod 600 "$client/ecdsa-p384.tamper.key"
  echo "generated $client/ecdsa-p384.tamper.key"
fi

# The broker's half. The tool holds the root secret, folds the ladder down to the
# date step, and reports the rung with the stage that names where it sits. The
# stage comes from the library rather than being written here, so there is only
# one statement of where the rung came from.
derived="$("$demo" derive --secret-file "$client/hmac.secret" --cluster "$cluster")"
rung="$(jq -r .rung <<<"$derived")"
rung_from="$(jq -r .from <<<"$derived")"
rung_date="$(jq -r '.scope.date' <<<"$derived")"
# Rendered from whatever scope the library reported rather than named key by key,
# so another step in the ladder needs no change here.
rung_scope="$(jq -r '.scope | to_entries[] | "        \(.key): \"\(.value)\""' <<<"$derived")"

# A rung is raw hash output rather than text, so it travels as base64. That is
# also why the server requires base64 whenever a stage is set: trimming a
# trailing newline off a plain secret would corrupt bytes that happen to end in
# one.
printf '%s' "$rung" >"$node/hmac-rung.b64"
chmod 600 "$node/hmac-rung.b64"

public_key="$(openssl ec -in "$client/ecdsa-p384.key" -pubout 2>/dev/null)"

# The API server is told the ladder, the two keys, and the identity each one
# authenticates as. Note the asymmetry the field names carry: a public key is
# inline because it is not a secret, and key material is referenced by path
# because it is.
#
# Scope values are quoted. A date unquoted is a valid YAML integer and the field
# is a string, so it would fail to decode.
{
  cat <<EOF
# Generated by gen-fixtures.sh. Mounted at /httpsig in the control plane node.
apiVersion: apiserver.config.k8s.io/v1
kind: AuthenticationConfiguration
httpSignature:
  # Verified against the created timestamp the signature carries, so a captured
  # request can be replayed only until it ages out of this window.
  maxAge: 1m
  # Stated identically here and in the client's kubeconfig. Both sides render it
  # from one definition in the demo tool, because a ladder that differs between
  # them fails as a signature mismatch and says nothing about why.
  keyDerivation:
EOF
  "$demo" ladder --indent "    "
  cat <<EOF
  keys:
  - keyID: demo-hmac
    algorithm: hmac-sha256
    # Not the root secret. A key folded through the date step, so this file is
    # useless for any day but the one its stage names.
    secretFile: /httpsig/hmac-rung.b64
    stage:
      from: $rung_from
      scope:
$rung_scope
    user:
      username: hmac-demo
      groups:
      - httpsig-demo
      - httpsig-hmac
  - keyID: demo-ecdsa-p384
    algorithm: ecdsa-p384-sha384
    publicKey: |
$(sed 's/^/      /' <<<"$public_key")
    user:
      username: ecdsa-demo
      groups:
      - httpsig-demo
      - httpsig-asymmetric
EOF
} >"$node/authentication-config.yaml"

echo "wrote $node/authentication-config.yaml"
echo "gen-fixtures.sh: the server's HMAC key is folded through $rung_from: bound to cluster"
echo "                 $cluster and to $rung_date (UTC). Rerun this and restart the API"
echo "                 server after that date rolls, or it stops verifying."
