#!/usr/bin/env bash

# Copyright The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Writes fixtures/kubeconfig with one user per demo key.
#
# Separate from up.sh so the same file can be produced without a cluster, which
# is how it gets validated before anything is built.
#
# Usage: write-kubeconfig.sh <server-url> <base64-ca-data>
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

server="${1:?server URL required}"
ca="${2:?base64 CA data required}"
demo="$PWD/fixtures/bin/httpsig-demo"
client="$PWD/fixtures/client"
# The same source gen-fixtures.sh reads it from. The client folds the ladder with
# this value; a different one derives a key the server cannot verify.
source ./env.sh
cluster="$HTTPSIG_CLUSTER"

# Note what is and is not in the httpSignature block. The algorithm and the TTL
# are here because they do not rotate. There is no key and no key ID, because
# those come from the plugin on every request. That split is the whole reason a
# rotating credential needs no kubeconfig edit.
cat >fixtures/kubeconfig <<EOF
# Generated by write-kubeconfig.sh.
apiVersion: v1
kind: Config
current-context: hmac
clusters:
- name: $cluster
  cluster:
    server: $server
    certificate-authority-data: $ca
contexts:
- name: hmac
  context: {cluster: $cluster, user: hmac}
- name: ecdsa
  context: {cluster: $cluster, user: ecdsa}
users:
- name: hmac
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      algorithm: hmac-sha256
      ttl: 30s
      # The same ladder the API server states. This client holds the root secret
      # and folds the whole chain on every request, using the date in the
      # signature's own created parameter, so the two agree even across a date
      # boundary. The server holds only the folded result for one day.
      keyDerivation:
$("$demo" ladder --indent "        ")
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: $demo
      args: [credential, --fixtures, $client, --cluster, $cluster]
      interactiveMode: Never
- name: ecdsa
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      algorithm: ecdsa-p384-sha384
      ttl: 30s
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: $demo
      args: [credential, --fixtures, $client, --cluster, $cluster]
      interactiveMode: Never
EOF
echo "wrote fixtures/kubeconfig for $server"
