#!/usr/bin/env bash

# Copyright The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Writes fixtures/kubeconfig with one user per demo key.
#
# Separate from up.sh so the same file can be produced without a cluster, which
# is how it gets validated before anything is built.
#
# Usage: write-kubeconfig.sh <server-url> <base64-ca-data>
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

server="${1:?server URL required}"
ca="${2:?base64 CA data required}"
demo="$PWD/fixtures/bin/httpsig-demo"
client="$PWD/fixtures/client"
# The same source gen-fixtures.sh reads it from. The client folds the ladder with
# this value; a different one derives a key the server cannot verify.
source ./env.sh
cluster="$HTTPSIG_CLUSTER"

# Note what is and is not in the httpSignature block. For the two configured keys
# the algorithm and the TTL are here because they do not rotate, and there is no key
# and no key ID because those come from the plugin on every request. That split is
# the whole reason a rotating credential needs no kubeconfig edit.
#
# The certificate users state even less: no algorithm, because the certificate's key
# type determines it, and no key ID, because it is the certificate's digest. Both are
# values with one correct answer, and a second copy of such a value is only somewhere
# for the two to disagree.
cat >fixtures/kubeconfig <<EOF
# Generated by write-kubeconfig.sh.
apiVersion: v1
kind: Config
current-context: hmac
clusters:
- name: $cluster
  cluster:
    server: $server
    certificate-authority-data: $ca
contexts:
- name: hmac
  context: {cluster: $cluster, user: hmac}
- name: ecdsa
  context: {cluster: $cluster, user: ecdsa}
- name: cert
  context: {cluster: $cluster, user: cert}
- name: bundle
  context: {cluster: $cluster, user: bundle}
- name: rogue
  context: {cluster: $cluster, user: rogue}
users:
- name: hmac
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      algorithm: hmac-sha256
      ttl: 30s
      # The same ladder the API server states. This client holds the root secret
      # and folds the whole chain on every request, using the date in the
      # signature's own created parameter, so the two agree even across a date
      # boundary. The server holds only the folded result for one day.
      keyDerivation:
$("$demo" ladder --indent "        ")
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: $demo
      args: [credential, --fixtures, $client, --cluster, $cluster]
      interactiveMode: Never
- name: ecdsa
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      algorithm: ecdsa-p384-sha384
      ttl: 30s
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: $demo
      args: [credential, --fixtures, $client, --cluster, $cluster]
      interactiveMode: Never
# The certificate is the assertion of who this client is. The server holds the
# authority that issued it and nothing about this client, so the identity comes from
# the certificate's own subject rather than from the server's configuration.
- name: cert
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      ttl: 30s
      certFile: $client/cert-demo.crt
      keyFile: $client/cert-demo.key
# The same certificate delivered as one document, key first then the chain, which is
# what a PodCertificateProjection writes. Preferred wherever it is available: two
# files can be read between the two writes of a rotation and one cannot.
- name: bundle
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      ttl: 30s
      credentialBundleFile: $client/cert-demo.bundle.pem
# A certificate from an authority the server was never given. Same subject, so it
# would map to the same identity; its signature verifies against its own key, so
# possession is not what is wrong with it. Only the trust anchor is.
- name: rogue
  user:
    httpSignature:
      apiVersion: client.authentication.k8s.io/v1alpha1
      ttl: 30s
      certFile: $client/rogue.crt
      keyFile: $client/rogue.key
EOF
# Validated with clientcmd's own loader, because a released kubectl would accept
# this file however wrong it is: kubeconfig parsing drops unrecognized fields, so an
# httpSignature block with a typo becomes a user with no credential and the request
# goes out unauthenticated. The check also builds each context's client, which is
# where the signing transport reads the key material.
HTTPSIG_KUBECONFIG="$PWD/fixtures/kubeconfig" \
  go test ../../httpsig/e2e/internal/configcheck/ -run TestGeneratedKubeconfig -count=1 >/dev/null || {
  echo "write-kubeconfig.sh: the generated kubeconfig is not usable." >&2
  echo "                     Rerun for the detail: HTTPSIG_KUBECONFIG=$PWD/fixtures/kubeconfig \\" >&2
  echo "                       go test ../../httpsig/e2e/internal/configcheck/ -run TestGeneratedKubeconfig -v" >&2
  exit 1
}
echo "wrote fixtures/kubeconfig for $server, and every context builds a signing client"
