/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
//Copyright The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// To regenerate api.pb.go run `hack/update-codegen.sh protobindings`

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: staging/src/k8s.io/externalhttpsig/apis/v1alpha1/api.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

type MetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key_derivation is the HMAC key derivation ladder this resolver's symmetric
	// material is derived through. Set it only if this resolver vends material
	// for hmac-sha256 that is a rung of a ladder rather than a whole secret.
	//
	// A ladder is not secret. It describes a derivation for a whole deployment,
	// and every party that derives states the same one: this resolver, and every
	// client that signs. kube-apiserver holds no copy of its own, so this is the
	// only statement of it the server sees. kube-apiserver logs a digest of the
	// parsed ladder and exposes it as a metric label, so an operator can compare
	// it against the digest a client logs for its own copy. Two parties that
	// disagree about a ladder otherwise fail as a bare signature mismatch, with
	// nothing in the error to say why.
	KeyDerivation *KeyDerivation `protobuf:"bytes,1,opt,name=key_derivation,json=keyDerivation,proto3" json:"key_derivation,omitempty"`
	// max_signature_age_seconds bounds how old any signature this resolver's keys
	// verify may be, measured from its created parameter. kube-apiserver applies
	// the smaller of this and its own configured maximum age, so this can only
	// narrow the replay window and never widen it. Zero or negative means this
	// resolver states no opinion.
	MaxSignatureAgeSeconds int64 `protobuf:"varint,2,opt,name=max_signature_age_seconds,json=maxSignatureAgeSeconds,proto3" json:"max_signature_age_seconds,omitempty"`
	// refresh_hint_seconds is how often kube-apiserver should call Metadata
	// again. The same call is the resolver's health check, so this also sets how
	// quickly an unhealthy resolver is noticed. Zero or negative means
	// kube-apiserver uses its own interval.
	RefreshHintSeconds int64 `protobuf:"varint,3,opt,name=refresh_hint_seconds,json=refreshHintSeconds,proto3" json:"refresh_hint_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetKeyDerivation() *KeyDerivation {
	if x != nil {
		return x.KeyDerivation
	}
	return nil
}

func (x *MetadataResponse) GetMaxSignatureAgeSeconds() int64 {
	if x != nil {
		return x.MaxSignatureAgeSeconds
	}
	return 0
}

func (x *MetadataResponse) GetRefreshHintSeconds() int64 {
	if x != nil {
		return x.RefreshHintSeconds
	}
	return 0
}

// KeyDerivation is an HMAC key derivation ladder: a chain of HMAC steps that
// turns a root secret into a signing key scoped to a purpose and, with a date
// step, to a day. It contains no secret.
//
// The field names and the closed sets of values here are the same ones a client
// states in its kubeconfig, so one ladder document describes both sides.
type KeyDerivation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind discriminates the derivation form. Only "hmac-ladder" is defined.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// hash is the HMAC hash used to derive: "sha-256" or "sha-512". The signature
	// algorithm is always hmac-sha256; this governs derivation only.
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// secret_prefix is prepended to the root secret before the first step. It
	// applies only when the material is the root secret, never to a rung.
	SecretPrefix string `protobuf:"bytes,3,opt,name=secret_prefix,json=secretPrefix,proto3" json:"secret_prefix,omitempty"`
	// steps are the rungs, applied in order. Each step's input is fed to HMAC
	// keyed by the previous step's output, and the last output is the key that
	// verifies a signature.
	Steps         []*KeyDerivationStep `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDerivation) Reset() {
	*x = KeyDerivation{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDerivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDerivation) ProtoMessage() {}

func (x *KeyDerivation) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDerivation.ProtoReflect.Descriptor instead.
func (*KeyDerivation) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{2}
}

func (x *KeyDerivation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KeyDerivation) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *KeyDerivation) GetSecretPrefix() string {
	if x != nil {
		return x.SecretPrefix
	}
	return ""
}

func (x *KeyDerivation) GetSteps() []*KeyDerivationStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// KeyDerivationStep is one rung of a ladder. Exactly one of literal, scope, or
// date supplies the step's input.
//
// Step names are arbitrary labels chosen by whoever writes the ladder. Nothing
// treats a name, a prefix, or a literal as meaningful.
type KeyDerivationStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the step. Names are unique within a ladder and key the
	// scope map of a DerivedKey. A name may not contain "/", because step values
	// are joined by slashes into the key ID a signature carries.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// literal is a fixed input value, the same for every party.
	Literal string `protobuf:"bytes,2,opt,name=literal,proto3" json:"literal,omitempty"`
	// scope marks the input as a deployment-scoped value, such as a cell or a
	// purpose name, supplied by each party's own position on the ladder.
	Scope bool `protobuf:"varint,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// date names a date format from a closed set: "YYYYMMDD" or "YYYY-MM-DD".
	// The input is the signature's created timestamp rendered in UTC, so a signer
	// and a verifier render the same value without consulting their own clocks.
	// The set is deliberately not a strftime or Go layout string: a ladder is
	// read by implementations in any language, and a format token has to mean the
	// same thing to all of them.
	Date          string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDerivationStep) Reset() {
	*x = KeyDerivationStep{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDerivationStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDerivationStep) ProtoMessage() {}

func (x *KeyDerivationStep) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDerivationStep.ProtoReflect.Descriptor instead.
func (*KeyDerivationStep) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{3}
}

func (x *KeyDerivationStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyDerivationStep) GetLiteral() string {
	if x != nil {
		return x.Literal
	}
	return ""
}

func (x *KeyDerivationStep) GetScope() bool {
	if x != nil {
		return x.Scope
	}
	return false
}

func (x *KeyDerivationStep) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ResolveKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key_id is the keyid parameter the signature carries, exactly as it appeared
	// on the wire. kube-apiserver does not parse it, beyond taking the segment
	// before the first "/" to decide which resolver to ask. A derived key's
	// key_id is the key's name followed by each ladder step's claimed value,
	// joined by "/", and decomposing that is this resolver's job because this
	// resolver is the party that holds the ladder.
	//
	// This is peer-chosen input of bounded length. Do not interpret it as a path,
	// a query, or a template.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// algorithm is the alg parameter the signature carries, named as in the IANA
	// "HTTP Signature Algorithms" registry: ed25519, ecdsa-p256-sha256,
	// ecdsa-p384-sha384, rsa-pss-sha512, rsa-v1_5-sha256, or hmac-sha256.
	//
	// It is advisory, and it is a claim. It lets a resolver holding more than one
	// key for a name choose, or reject early. The authoritative algorithm is the
	// one this resolver states in the response, which kube-apiserver checks the
	// signature's claim against.
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// created is the created parameter the signature carries. A resolver that
	// vends date-scoped material derives for this date rather than for its own
	// clock, so that a signature created either side of a date boundary resolves
	// to the key it was signed with.
	//
	// kube-apiserver has already rejected a signature whose created is outside
	// its configured maximum age and clock tolerance, so this is bounded, but it
	// is still a value the peer chose within those bounds.
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	// relayed_headers holds values for the request headers kube-apiserver is
	// configured to relay, keyed by lowercase header name. Nothing else about the
	// request is sent: not the method, not the path, not the body.
	//
	// This is how key material or tenancy context can travel in a request header
	// rather than sitting in a file, such as a rotating session token. Two rules
	// make it safe to have. kube-apiserver relays only the headers its own
	// configuration names, so a resolver cannot ask for more of the request. And
	// a relayed header must be covered by the signature, which kube-apiserver
	// checks before dispatching this call, so an intermediary cannot inject one.
	//
	// Covered is not the same as verified. Verification needs the key this call
	// returns, so at the time this call is made the value is still only a claim.
	RelayedHeaders map[string]string `protobuf:"bytes,4,rep,name=relayed_headers,json=relayedHeaders,proto3" json:"relayed_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// uid is a unique identifier for this call, for correlating a resolver's logs
	// with kube-apiserver's. It identifies the call, not the request, not the key,
	// and not the user.
	Uid string `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	// api_server_id is the identity of the calling kube-apiserver, for a
	// resolver's own audit trail.
	ApiServerId   string `protobuf:"bytes,6,opt,name=api_server_id,json=apiServerId,proto3" json:"api_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKeyRequest) Reset() {
	*x = ResolveKeyRequest{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKeyRequest) ProtoMessage() {}

func (x *ResolveKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKeyRequest.ProtoReflect.Descriptor instead.
func (*ResolveKeyRequest) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ResolveKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ResolveKeyRequest) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ResolveKeyRequest) GetRelayedHeaders() map[string]string {
	if x != nil {
		return x.RelayedHeaders
	}
	return nil
}

func (x *ResolveKeyRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResolveKeyRequest) GetApiServerId() string {
	if x != nil {
		return x.ApiServerId
	}
	return ""
}

type ResolveKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// algorithm is the algorithm this key verifies, named as in the IANA "HTTP
	// Signature Algorithms" registry. Required.
	//
	// This is the authoritative value and the signature's own alg claim is
	// checked against it. Without it a peer could claim hmac-sha256 for a key
	// whose material is an asymmetric public key and have the public key treated
	// as a shared secret, which is the algorithm confusion class of attack. A
	// resolver that echoes the request's algorithm rather than stating its key's
	// own reopens that.
	Algorithm string `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Exactly one of these carries the key material, and which one is determined
	// by algorithm: public_key for the asymmetric algorithms, secret or
	// derived_key for hmac-sha256.
	//
	// Types that are valid to be assigned to Material:
	//
	//	*ResolveKeyResponse_PublicKey
	//	*ResolveKeyResponse_Secret
	//	*ResolveKeyResponse_DerivedKey
	Material isResolveKeyResponse_Material `protobuf_oneof:"material"`
	// user is the identity a request signed by this key authenticates as.
	// Required.
	//
	// This is a claim crossing a trust boundary, not a conclusion.
	// kube-apiserver validates it on arrival and rejects an empty username, and
	// any username or group under the "system:" prefix, which is reserved for
	// identities Kubernetes issues. No prefix is added, so a resolver operator
	// owns avoiding collision with names other authenticators issue.
	User *UserInfo `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	// cache_ttl_seconds is how long kube-apiserver may reuse this response
	// without calling again. Zero or negative means do not cache, which is the
	// right answer when the response depended on a relayed header value that
	// rotates.
	//
	// A cached key stays usable after it is revoked, so this is the revocation
	// window and this resolver sets it. kube-apiserver caps it by its own
	// configured maximum, and caches nothing longer.
	CacheTtlSeconds int64 `protobuf:"varint,6,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	// max_signature_age_seconds bounds how old a signature verified by this key
	// may be. kube-apiserver applies the smallest of this, the value in
	// MetadataResponse, and its own configured maximum, so this can only narrow
	// the replay window for this one key. Zero or negative means no opinion.
	MaxSignatureAgeSeconds int64 `protobuf:"varint,7,opt,name=max_signature_age_seconds,json=maxSignatureAgeSeconds,proto3" json:"max_signature_age_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResolveKeyResponse) Reset() {
	*x = ResolveKeyResponse{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKeyResponse) ProtoMessage() {}

func (x *ResolveKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKeyResponse.ProtoReflect.Descriptor instead.
func (*ResolveKeyResponse) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ResolveKeyResponse) GetMaterial() isResolveKeyResponse_Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *ResolveKeyResponse) GetPublicKey() []byte {
	if x != nil {
		if x, ok := x.Material.(*ResolveKeyResponse_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *ResolveKeyResponse) GetSecret() []byte {
	if x != nil {
		if x, ok := x.Material.(*ResolveKeyResponse_Secret); ok {
			return x.Secret
		}
	}
	return nil
}

func (x *ResolveKeyResponse) GetDerivedKey() *DerivedKey {
	if x != nil {
		if x, ok := x.Material.(*ResolveKeyResponse_DerivedKey); ok {
			return x.DerivedKey
		}
	}
	return nil
}

func (x *ResolveKeyResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ResolveKeyResponse) GetCacheTtlSeconds() int64 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

func (x *ResolveKeyResponse) GetMaxSignatureAgeSeconds() int64 {
	if x != nil {
		return x.MaxSignatureAgeSeconds
	}
	return 0
}

type isResolveKeyResponse_Material interface {
	isResolveKeyResponse_Material()
}

type ResolveKeyResponse_PublicKey struct {
	// public_key is a public key in PKIX, ASN.1 DER form, the encoding
	// x509.MarshalPKIXPublicKey produces. Not PEM: a PEM block type is a
	// second statement of the key kind and a second thing to disagree with
	// algorithm. A public key is not secret.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type ResolveKeyResponse_Secret struct {
	// secret is a shared secret for hmac-sha256, used as given with no
	// derivation. Any ladder in Metadata does not apply to it.
	//
	// A shared secret lets whoever holds it produce signatures
	// indistinguishable from the client's. Prefer derived_key, which bounds
	// that, or an asymmetric algorithm, which removes it.
	Secret []byte `protobuf:"bytes,3,opt,name=secret,proto3,oneof"`
}

type ResolveKeyResponse_DerivedKey struct {
	// derived_key is a rung of the ladder Metadata states, together with its
	// position on that ladder. kube-apiserver folds the remaining steps per
	// request, using the signature's created timestamp for any date step.
	//
	// This bounds what a compromise of kube-apiserver's memory yields: only
	// what the rung's scope covers, and for a rung past a date step, only
	// until that date rolls.
	DerivedKey *DerivedKey `protobuf:"bytes,4,opt,name=derived_key,json=derivedKey,proto3,oneof"`
}

func (*ResolveKeyResponse_PublicKey) isResolveKeyResponse_Material() {}

func (*ResolveKeyResponse_Secret) isResolveKeyResponse_Material() {}

func (*ResolveKeyResponse_DerivedKey) isResolveKeyResponse_Material() {}

// DerivedKey is a rung of a key derivation ladder and its position on it. The
// bytes of derived material cannot say what was folded into them, so the position
// travels with them.
type DerivedKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the rung: the raw output of the step named by from. Required.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// from names the ladder step whose output key is. Empty means key is the root
	// secret and kube-apiserver folds the whole ladder per request.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// scope holds values for the ladder's scope steps, and assertions for the
	// date steps at or before from, keyed by step name.
	//
	// A value for a step at or before from asserts what is already folded into
	// key; a value for a scope step after from is an input still to be folded. It
	// must cover exactly those. A missing value and an unexpected value are both
	// errors, because either one means this resolver and kube-apiserver disagree
	// about what the material is.
	Scope         map[string]string `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DerivedKey) Reset() {
	*x = DerivedKey{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivedKey) ProtoMessage() {}

func (x *DerivedKey) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivedKey.ProtoReflect.Descriptor instead.
func (*DerivedKey) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{6}
}

func (x *DerivedKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DerivedKey) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DerivedKey) GetScope() map[string]string {
	if x != nil {
		return x.Scope
	}
	return nil
}

// UserInfo is an identity a key authenticates as.
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the user name. Required, and must not begin with "system:".
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// uid is a unique identifier for the user.
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// groups are the groups the user belongs to. No group may begin with
	// "system:". The "system:authenticated" group is added by kube-apiserver and
	// does not need to be listed.
	Groups []string `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	// extra holds additional information about the user, keyed by an arbitrary
	// name. kube-apiserver passes it to authorization and records it in the audit
	// log without interpreting it.
	Extra         map[string]*ExtraValue `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserInfo) GetExtra() map[string]*ExtraValue {
	if x != nil {
		return x.Extra
	}
	return nil
}

// ExtraValue is the multi-valued form every value in UserInfo.extra takes, because
// proto3 maps cannot hold a repeated value directly.
type ExtraValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraValue) Reset() {
	*x = ExtraValue{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraValue) ProtoMessage() {}

func (x *ExtraValue) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraValue.ProtoReflect.Descriptor instead.
func (*ExtraValue) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{8}
}

func (x *ExtraValue) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConsumeNonceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key_id is the keyid parameter of the signature that carried this nonce,
	// exactly as it appeared on the wire. Nonces are scoped per key: the same
	// nonce value used by two different keys is two different facts, and a
	// resolver that pooled them would let one client's traffic reject another's.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// nonce is the nonce parameter the signature carries. Unlike everything in a
	// ResolveKeyRequest, this arrives having been covered by a signature that
	// already verified, so it is the value the key holder chose.
	Nonce string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// created is the created parameter the signature carries.
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	// expires_at is when kube-apiserver will stop accepting any signature bearing
	// this nonce, being created plus the effective maximum signature age plus the
	// configured clock tolerance. A resolver may forget the nonce after this and
	// still be correct; forgetting it earlier reopens the replay window.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// uid is a unique identifier for this call, for correlating logs. It
	// identifies the call, not the request.
	Uid string `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	// api_server_id is the identity of the calling kube-apiserver.
	ApiServerId   string `protobuf:"bytes,6,opt,name=api_server_id,json=apiServerId,proto3" json:"api_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeNonceRequest) Reset() {
	*x = ConsumeNonceRequest{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeNonceRequest) ProtoMessage() {}

func (x *ConsumeNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeNonceRequest.ProtoReflect.Descriptor instead.
func (*ConsumeNonceRequest) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeNonceRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ConsumeNonceRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ConsumeNonceRequest) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ConsumeNonceRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ConsumeNonceRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ConsumeNonceRequest) GetApiServerId() string {
	if x != nil {
		return x.ApiServerId
	}
	return ""
}

type ConsumeNonceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted reports that this nonce had not been used for this key and has now
	// been recorded. False means the request is rejected as a replay.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// reason describes why accepted is false, for kube-apiserver's log. It states
	// a policy outcome, such as a nonce having been seen before. It is not the
	// place for a transport or storage failure: those belong in the gRPC status,
	// where kube-apiserver counts them separately, because a resolver outage
	// reported as a rejection reads in the logs as a replay attack.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeNonceResponse) Reset() {
	*x = ConsumeNonceResponse{}
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeNonceResponse) ProtoMessage() {}

func (x *ConsumeNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeNonceResponse.ProtoReflect.Descriptor instead.
func (*ConsumeNonceResponse) Descriptor() ([]byte, []int) {
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeNonceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConsumeNonceResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto protoreflect.FileDescriptor

const file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	":staging/src/k8s.io/externalhttpsig/apis/v1alpha1/api.proto\x12\bv1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fMetadataRequest\"\xbf\x01\n" +
	"\x10MetadataResponse\x12>\n" +
	"\x0ekey_derivation\x18\x01 \x01(\v2\x17.v1alpha1.KeyDerivationR\rkeyDerivation\x129\n" +
	"\x19max_signature_age_seconds\x18\x02 \x01(\x03R\x16maxSignatureAgeSeconds\x120\n" +
	"\x14refresh_hint_seconds\x18\x03 \x01(\x03R\x12refreshHintSeconds\"\x8f\x01\n" +
	"\rKeyDerivation\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12#\n" +
	"\rsecret_prefix\x18\x03 \x01(\tR\fsecretPrefix\x121\n" +
	"\x05steps\x18\x04 \x03(\v2\x1b.v1alpha1.KeyDerivationStepR\x05steps\"k\n" +
	"\x11KeyDerivationStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aliteral\x18\x02 \x01(\tR\aliteral\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\bR\x05scope\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"\xd1\x02\n" +
	"\x11ResolveKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12X\n" +
	"\x0frelayed_headers\x18\x04 \x03(\v2/.v1alpha1.ResolveKeyRequest.RelayedHeadersEntryR\x0erelayedHeaders\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\"\n" +
	"\rapi_server_id\x18\x06 \x01(\tR\vapiServerId\x1aA\n" +
	"\x13RelayedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\x12ResolveKeyResponse\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1f\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fH\x00R\tpublicKey\x12\x18\n" +
	"\x06secret\x18\x03 \x01(\fH\x00R\x06secret\x127\n" +
	"\vderived_key\x18\x04 \x01(\v2\x14.v1alpha1.DerivedKeyH\x00R\n" +
	"derivedKey\x12&\n" +
	"\x04user\x18\x05 \x01(\v2\x12.v1alpha1.UserInfoR\x04user\x12*\n" +
	"\x11cache_ttl_seconds\x18\x06 \x01(\x03R\x0fcacheTtlSeconds\x129\n" +
	"\x19max_signature_age_seconds\x18\a \x01(\x03R\x16maxSignatureAgeSecondsB\n" +
	"\n" +
	"\bmaterial\"\xa3\x01\n" +
	"\n" +
	"DerivedKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x125\n" +
	"\x05scope\x18\x03 \x03(\v2\x1f.v1alpha1.DerivedKey.ScopeEntryR\x05scope\x1a8\n" +
	"\n" +
	"ScopeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\bUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x123\n" +
	"\x05extra\x18\x04 \x03(\v2\x1d.v1alpha1.UserInfo.ExtraEntryR\x05extra\x1aN\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.v1alpha1.ExtraValueR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"ExtraValue\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\xe9\x01\n" +
	"\x13ConsumeNonceRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\"\n" +
	"\rapi_server_id\x18\x06 \x01(\tR\vapiServerId\"J\n" +
	"\x14ConsumeNonceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xff\x01\n" +
	"\x1cExternalHTTPSignatureService\x12C\n" +
	"\bMetadata\x12\x19.v1alpha1.MetadataRequest\x1a\x1a.v1alpha1.MetadataResponse\"\x00\x12I\n" +
	"\n" +
	"ResolveKey\x12\x1b.v1alpha1.ResolveKeyRequest\x1a\x1c.v1alpha1.ResolveKeyResponse\"\x00\x12O\n" +
	"\fConsumeNonce\x12\x1d.v1alpha1.ConsumeNonceRequest\x1a\x1e.v1alpha1.ConsumeNonceResponse\"\x00B&Z$k8s.io/externalhttpsig/apis/v1alpha1b\x06proto3"

var (
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescOnce sync.Once
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescData []byte
)

func file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDesc), len(file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDesc)))
	})
	return file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDescData
}

var file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_goTypes = []any{
	(*MetadataRequest)(nil),       // 0: v1alpha1.MetadataRequest
	(*MetadataResponse)(nil),      // 1: v1alpha1.MetadataResponse
	(*KeyDerivation)(nil),         // 2: v1alpha1.KeyDerivation
	(*KeyDerivationStep)(nil),     // 3: v1alpha1.KeyDerivationStep
	(*ResolveKeyRequest)(nil),     // 4: v1alpha1.ResolveKeyRequest
	(*ResolveKeyResponse)(nil),    // 5: v1alpha1.ResolveKeyResponse
	(*DerivedKey)(nil),            // 6: v1alpha1.DerivedKey
	(*UserInfo)(nil),              // 7: v1alpha1.UserInfo
	(*ExtraValue)(nil),            // 8: v1alpha1.ExtraValue
	(*ConsumeNonceRequest)(nil),   // 9: v1alpha1.ConsumeNonceRequest
	(*ConsumeNonceResponse)(nil),  // 10: v1alpha1.ConsumeNonceResponse
	nil,                           // 11: v1alpha1.ResolveKeyRequest.RelayedHeadersEntry
	nil,                           // 12: v1alpha1.DerivedKey.ScopeEntry
	nil,                           // 13: v1alpha1.UserInfo.ExtraEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_depIdxs = []int32{
	2,  // 0: v1alpha1.MetadataResponse.key_derivation:type_name -> v1alpha1.KeyDerivation
	3,  // 1: v1alpha1.KeyDerivation.steps:type_name -> v1alpha1.KeyDerivationStep
	14, // 2: v1alpha1.ResolveKeyRequest.created:type_name -> google.protobuf.Timestamp
	11, // 3: v1alpha1.ResolveKeyRequest.relayed_headers:type_name -> v1alpha1.ResolveKeyRequest.RelayedHeadersEntry
	6,  // 4: v1alpha1.ResolveKeyResponse.derived_key:type_name -> v1alpha1.DerivedKey
	7,  // 5: v1alpha1.ResolveKeyResponse.user:type_name -> v1alpha1.UserInfo
	12, // 6: v1alpha1.DerivedKey.scope:type_name -> v1alpha1.DerivedKey.ScopeEntry
	13, // 7: v1alpha1.UserInfo.extra:type_name -> v1alpha1.UserInfo.ExtraEntry
	14, // 8: v1alpha1.ConsumeNonceRequest.created:type_name -> google.protobuf.Timestamp
	14, // 9: v1alpha1.ConsumeNonceRequest.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 10: v1alpha1.UserInfo.ExtraEntry.value:type_name -> v1alpha1.ExtraValue
	0,  // 11: v1alpha1.ExternalHTTPSignatureService.Metadata:input_type -> v1alpha1.MetadataRequest
	4,  // 12: v1alpha1.ExternalHTTPSignatureService.ResolveKey:input_type -> v1alpha1.ResolveKeyRequest
	9,  // 13: v1alpha1.ExternalHTTPSignatureService.ConsumeNonce:input_type -> v1alpha1.ConsumeNonceRequest
	1,  // 14: v1alpha1.ExternalHTTPSignatureService.Metadata:output_type -> v1alpha1.MetadataResponse
	5,  // 15: v1alpha1.ExternalHTTPSignatureService.ResolveKey:output_type -> v1alpha1.ResolveKeyResponse
	10, // 16: v1alpha1.ExternalHTTPSignatureService.ConsumeNonce:output_type -> v1alpha1.ConsumeNonceResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_init() }
func file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_init() {
	if File_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto != nil {
		return
	}
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes[5].OneofWrappers = []any{
		(*ResolveKeyResponse_PublicKey)(nil),
		(*ResolveKeyResponse_Secret)(nil),
		(*ResolveKeyResponse_DerivedKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDesc), len(file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto = out.File
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_goTypes = nil
	file_staging_src_k8s_io_externalhttpsig_apis_v1alpha1_api_proto_depIdxs = nil
}
