/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
//Copyright The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// To regenerate api.pb.go run `hack/update-codegen.sh protobindings`

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.23.4
// source: staging/src/k8s.io/externalhttpsig/apis/v1alpha1/api.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalHTTPSignatureService_Metadata_FullMethodName     = "/v1alpha1.ExternalHTTPSignatureService/Metadata"
	ExternalHTTPSignatureService_ResolveKey_FullMethodName   = "/v1alpha1.ExternalHTTPSignatureService/ResolveKey"
	ExternalHTTPSignatureService_ConsumeNonce_FullMethodName = "/v1alpha1.ExternalHTTPSignatureService/ConsumeNonce"
)

// ExternalHTTPSignatureServiceClient is the client API for ExternalHTTPSignatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is served by a process on a local Unix Domain Socket. It resolves
// the keys that verify HTTP message signatures (RFC 9421) on requests to
// kube-apiserver, and it records the nonces those signatures carry.
//
// The division of labor is fixed and is the reason this API is worth having.
// kube-apiserver does all of the cryptography: it builds the signature base,
// verifies the signature, enforces which components a signature must cover, and
// checks the body digest. A resolver holds key material and nonce state. It
// never sees a request and it never decides whether a signature is valid.
//
// Two consequences follow, and an implementation that ignores either is unsafe:
//
// Every value in a ResolveKeyRequest is an unverified claim. The request is
// dispatched before any signature has been verified, because verifying requires
// the key this call returns. A key ID, an algorithm, and a relayed header value
// are all peer-chosen input. Treat them as lookup input, never as authorization.
//
// A ConsumeNonce call must be an atomic check-and-record, not a read. Several
// kube-apiservers front one cluster and each will call this for the same
// signature at most once. If two concurrent calls for the same key ID and nonce
// can both return accepted, the replay window is as wide as the number of API
// servers, which is the situation this RPC exists to close.
type ExternalHTTPSignatureServiceClient interface {
	// Metadata is called once at startup, and then polled as a health check.
	//
	// It carries the facts about a resolver that are not per key: the key
	// derivation ladder its symmetric material is derived through, and any
	// narrowing of signature age it wants to impose. kube-apiserver will not
	// serve signature-authenticated requests for this resolver until one call
	// has succeeded, so a resolver that cannot yet answer should fail rather
	// than answer with defaults.
	Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// ResolveKey returns the key that verifies signatures bearing a key ID, and
	// the identity a request so signed authenticates as.
	//
	// kube-apiserver calls this for a key ID it has no cached answer for, and
	// caches the response for the duration the response states. Return NOT_FOUND
	// for a key ID this resolver does not serve or no longer serves: a key that
	// has been revoked is a key that does not resolve. Do not return a response
	// that describes the absence of a key, because a caller that mishandles such
	// a response authenticates a request it should have rejected.
	ResolveKey(ctx context.Context, in *ResolveKeyRequest, opts ...grpc.CallOption) (*ResolveKeyResponse, error)
	// ConsumeNonce records that a nonce has been used for a key, and reports
	// whether it had been used already.
	//
	// kube-apiserver calls this only after a signature has verified, so unlike
	// ResolveKey this is not reachable by an unauthenticated caller. It is called
	// at most once per accepted request.
	//
	// This must be atomic: two concurrent calls with the same key ID and nonce
	// must not both return accepted. An implementation may forget a nonce once
	// the expires_at the request carries has passed, because kube-apiserver will
	// not accept a signature bearing it after that.
	//
	// An error, including an unreachable resolver, causes kube-apiserver to
	// reject the request. There is no configuration that makes it accept one
	// instead: anti-replay that can be turned off by making this call fail is
	// not anti-replay.
	ConsumeNonce(ctx context.Context, in *ConsumeNonceRequest, opts ...grpc.CallOption) (*ConsumeNonceResponse, error)
}

type externalHTTPSignatureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalHTTPSignatureServiceClient(cc grpc.ClientConnInterface) ExternalHTTPSignatureServiceClient {
	return &externalHTTPSignatureServiceClient{cc}
}

func (c *externalHTTPSignatureServiceClient) Metadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, ExternalHTTPSignatureService_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalHTTPSignatureServiceClient) ResolveKey(ctx context.Context, in *ResolveKeyRequest, opts ...grpc.CallOption) (*ResolveKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveKeyResponse)
	err := c.cc.Invoke(ctx, ExternalHTTPSignatureService_ResolveKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalHTTPSignatureServiceClient) ConsumeNonce(ctx context.Context, in *ConsumeNonceRequest, opts ...grpc.CallOption) (*ConsumeNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeNonceResponse)
	err := c.cc.Invoke(ctx, ExternalHTTPSignatureService_ConsumeNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalHTTPSignatureServiceServer is the server API for ExternalHTTPSignatureService service.
// All implementations must embed UnimplementedExternalHTTPSignatureServiceServer
// for forward compatibility.
//
// This service is served by a process on a local Unix Domain Socket. It resolves
// the keys that verify HTTP message signatures (RFC 9421) on requests to
// kube-apiserver, and it records the nonces those signatures carry.
//
// The division of labor is fixed and is the reason this API is worth having.
// kube-apiserver does all of the cryptography: it builds the signature base,
// verifies the signature, enforces which components a signature must cover, and
// checks the body digest. A resolver holds key material and nonce state. It
// never sees a request and it never decides whether a signature is valid.
//
// Two consequences follow, and an implementation that ignores either is unsafe:
//
// Every value in a ResolveKeyRequest is an unverified claim. The request is
// dispatched before any signature has been verified, because verifying requires
// the key this call returns. A key ID, an algorithm, and a relayed header value
// are all peer-chosen input. Treat them as lookup input, never as authorization.
//
// A ConsumeNonce call must be an atomic check-and-record, not a read. Several
// kube-apiservers front one cluster and each will call this for the same
// signature at most once. If two concurrent calls for the same key ID and nonce
// can both return accepted, the replay window is as wide as the number of API
// servers, which is the situation this RPC exists to close.
type ExternalHTTPSignatureServiceServer interface {
	// Metadata is called once at startup, and then polled as a health check.
	//
	// It carries the facts about a resolver that are not per key: the key
	// derivation ladder its symmetric material is derived through, and any
	// narrowing of signature age it wants to impose. kube-apiserver will not
	// serve signature-authenticated requests for this resolver until one call
	// has succeeded, so a resolver that cannot yet answer should fail rather
	// than answer with defaults.
	Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// ResolveKey returns the key that verifies signatures bearing a key ID, and
	// the identity a request so signed authenticates as.
	//
	// kube-apiserver calls this for a key ID it has no cached answer for, and
	// caches the response for the duration the response states. Return NOT_FOUND
	// for a key ID this resolver does not serve or no longer serves: a key that
	// has been revoked is a key that does not resolve. Do not return a response
	// that describes the absence of a key, because a caller that mishandles such
	// a response authenticates a request it should have rejected.
	ResolveKey(context.Context, *ResolveKeyRequest) (*ResolveKeyResponse, error)
	// ConsumeNonce records that a nonce has been used for a key, and reports
	// whether it had been used already.
	//
	// kube-apiserver calls this only after a signature has verified, so unlike
	// ResolveKey this is not reachable by an unauthenticated caller. It is called
	// at most once per accepted request.
	//
	// This must be atomic: two concurrent calls with the same key ID and nonce
	// must not both return accepted. An implementation may forget a nonce once
	// the expires_at the request carries has passed, because kube-apiserver will
	// not accept a signature bearing it after that.
	//
	// An error, including an unreachable resolver, causes kube-apiserver to
	// reject the request. There is no configuration that makes it accept one
	// instead: anti-replay that can be turned off by making this call fail is
	// not anti-replay.
	ConsumeNonce(context.Context, *ConsumeNonceRequest) (*ConsumeNonceResponse, error)
	mustEmbedUnimplementedExternalHTTPSignatureServiceServer()
}

// UnimplementedExternalHTTPSignatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalHTTPSignatureServiceServer struct{}

func (UnimplementedExternalHTTPSignatureServiceServer) Metadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedExternalHTTPSignatureServiceServer) ResolveKey(context.Context, *ResolveKeyRequest) (*ResolveKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveKey not implemented")
}
func (UnimplementedExternalHTTPSignatureServiceServer) ConsumeNonce(context.Context, *ConsumeNonceRequest) (*ConsumeNonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumeNonce not implemented")
}
func (UnimplementedExternalHTTPSignatureServiceServer) mustEmbedUnimplementedExternalHTTPSignatureServiceServer() {
}
func (UnimplementedExternalHTTPSignatureServiceServer) testEmbeddedByValue() {}

// UnsafeExternalHTTPSignatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalHTTPSignatureServiceServer will
// result in compilation errors.
type UnsafeExternalHTTPSignatureServiceServer interface {
	mustEmbedUnimplementedExternalHTTPSignatureServiceServer()
}

func RegisterExternalHTTPSignatureServiceServer(s grpc.ServiceRegistrar, srv ExternalHTTPSignatureServiceServer) {
	// If the following call panics, it indicates UnimplementedExternalHTTPSignatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalHTTPSignatureService_ServiceDesc, srv)
}

func _ExternalHTTPSignatureService_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalHTTPSignatureServiceServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalHTTPSignatureService_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalHTTPSignatureServiceServer).Metadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalHTTPSignatureService_ResolveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalHTTPSignatureServiceServer).ResolveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalHTTPSignatureService_ResolveKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalHTTPSignatureServiceServer).ResolveKey(ctx, req.(*ResolveKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalHTTPSignatureService_ConsumeNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalHTTPSignatureServiceServer).ConsumeNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalHTTPSignatureService_ConsumeNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalHTTPSignatureServiceServer).ConsumeNonce(ctx, req.(*ConsumeNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalHTTPSignatureService_ServiceDesc is the grpc.ServiceDesc for ExternalHTTPSignatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalHTTPSignatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha1.ExternalHTTPSignatureService",
	HandlerType: (*ExternalHTTPSignatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metadata",
			Handler:    _ExternalHTTPSignatureService_Metadata_Handler,
		},
		{
			MethodName: "ResolveKey",
			Handler:    _ExternalHTTPSignatureService_ResolveKey_Handler,
		},
		{
			MethodName: "ConsumeNonce",
			Handler:    _ExternalHTTPSignatureService_ConsumeNonce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staging/src/k8s.io/externalhttpsig/apis/v1alpha1/api.proto",
}
