//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clientauthentication "k8s.io/client-go/pkg/apis/clientauthentication"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Cluster)(nil), (*clientauthentication.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Cluster_To_clientauthentication_Cluster(a.(*Cluster), b.(*clientauthentication.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.Cluster)(nil), (*Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_Cluster_To_v1_Cluster(a.(*clientauthentication.Cluster), b.(*Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecCredential)(nil), (*clientauthentication.ExecCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ExecCredential_To_clientauthentication_ExecCredential(a.(*ExecCredential), b.(*clientauthentication.ExecCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.ExecCredential)(nil), (*ExecCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_ExecCredential_To_v1_ExecCredential(a.(*clientauthentication.ExecCredential), b.(*ExecCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecCredentialSpec)(nil), (*clientauthentication.ExecCredentialSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec(a.(*ExecCredentialSpec), b.(*clientauthentication.ExecCredentialSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.ExecCredentialSpec)(nil), (*ExecCredentialSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec(a.(*clientauthentication.ExecCredentialSpec), b.(*ExecCredentialSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecCredentialStatus)(nil), (*clientauthentication.ExecCredentialStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ExecCredentialStatus_To_clientauthentication_ExecCredentialStatus(a.(*ExecCredentialStatus), b.(*clientauthentication.ExecCredentialStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.ExecCredentialStatus)(nil), (*ExecCredentialStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_ExecCredentialStatus_To_v1_ExecCredentialStatus(a.(*clientauthentication.ExecCredentialStatus), b.(*ExecCredentialStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureCredential)(nil), (*clientauthentication.HTTPSignatureCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureCredential_To_clientauthentication_HTTPSignatureCredential(a.(*HTTPSignatureCredential), b.(*clientauthentication.HTTPSignatureCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureCredential)(nil), (*HTTPSignatureCredential)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureCredential_To_v1_HTTPSignatureCredential(a.(*clientauthentication.HTTPSignatureCredential), b.(*HTTPSignatureCredential), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureHeader)(nil), (*clientauthentication.HTTPSignatureHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureHeader_To_clientauthentication_HTTPSignatureHeader(a.(*HTTPSignatureHeader), b.(*clientauthentication.HTTPSignatureHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureHeader)(nil), (*HTTPSignatureHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureHeader_To_v1_HTTPSignatureHeader(a.(*clientauthentication.HTTPSignatureHeader), b.(*HTTPSignatureHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureKeyDerivation)(nil), (*clientauthentication.HTTPSignatureKeyDerivation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureKeyDerivation_To_clientauthentication_HTTPSignatureKeyDerivation(a.(*HTTPSignatureKeyDerivation), b.(*clientauthentication.HTTPSignatureKeyDerivation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureKeyDerivation)(nil), (*HTTPSignatureKeyDerivation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureKeyDerivation_To_v1_HTTPSignatureKeyDerivation(a.(*clientauthentication.HTTPSignatureKeyDerivation), b.(*HTTPSignatureKeyDerivation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureKeyDerivationStep)(nil), (*clientauthentication.HTTPSignatureKeyDerivationStep)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureKeyDerivationStep_To_clientauthentication_HTTPSignatureKeyDerivationStep(a.(*HTTPSignatureKeyDerivationStep), b.(*clientauthentication.HTTPSignatureKeyDerivationStep), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureKeyDerivationStep)(nil), (*HTTPSignatureKeyDerivationStep)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureKeyDerivationStep_To_v1_HTTPSignatureKeyDerivationStep(a.(*clientauthentication.HTTPSignatureKeyDerivationStep), b.(*HTTPSignatureKeyDerivationStep), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureRequest)(nil), (*clientauthentication.HTTPSignatureRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureRequest_To_clientauthentication_HTTPSignatureRequest(a.(*HTTPSignatureRequest), b.(*clientauthentication.HTTPSignatureRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureRequest)(nil), (*HTTPSignatureRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureRequest_To_v1_HTTPSignatureRequest(a.(*clientauthentication.HTTPSignatureRequest), b.(*HTTPSignatureRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HTTPSignatureStage)(nil), (*clientauthentication.HTTPSignatureStage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HTTPSignatureStage_To_clientauthentication_HTTPSignatureStage(a.(*HTTPSignatureStage), b.(*clientauthentication.HTTPSignatureStage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*clientauthentication.HTTPSignatureStage)(nil), (*HTTPSignatureStage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_clientauthentication_HTTPSignatureStage_To_v1_HTTPSignatureStage(a.(*clientauthentication.HTTPSignatureStage), b.(*HTTPSignatureStage), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Cluster_To_clientauthentication_Cluster(in *Cluster, out *clientauthentication.Cluster, s conversion.Scope) error {
	out.Server = in.Server
	out.TLSServerName = in.TLSServerName
	out.InsecureSkipTLSVerify = in.InsecureSkipTLSVerify
	out.CertificateAuthorityData = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthorityData))
	out.ProxyURL = in.ProxyURL
	out.DisableCompression = in.DisableCompression
	if err := runtime.Convert_runtime_RawExtension_To_runtime_Object(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Cluster_To_clientauthentication_Cluster is an autogenerated conversion function.
func Convert_v1_Cluster_To_clientauthentication_Cluster(in *Cluster, out *clientauthentication.Cluster, s conversion.Scope) error {
	return autoConvert_v1_Cluster_To_clientauthentication_Cluster(in, out, s)
}

func autoConvert_clientauthentication_Cluster_To_v1_Cluster(in *clientauthentication.Cluster, out *Cluster, s conversion.Scope) error {
	out.Server = in.Server
	out.TLSServerName = in.TLSServerName
	out.InsecureSkipTLSVerify = in.InsecureSkipTLSVerify
	out.CertificateAuthorityData = *(*[]byte)(unsafe.Pointer(&in.CertificateAuthorityData))
	out.ProxyURL = in.ProxyURL
	out.DisableCompression = in.DisableCompression
	if err := runtime.Convert_runtime_Object_To_runtime_RawExtension(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_clientauthentication_Cluster_To_v1_Cluster is an autogenerated conversion function.
func Convert_clientauthentication_Cluster_To_v1_Cluster(in *clientauthentication.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_clientauthentication_Cluster_To_v1_Cluster(in, out, s)
}

func autoConvert_v1_ExecCredential_To_clientauthentication_ExecCredential(in *ExecCredential, out *clientauthentication.ExecCredential, s conversion.Scope) error {
	if err := Convert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*clientauthentication.ExecCredentialStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1_ExecCredential_To_clientauthentication_ExecCredential is an autogenerated conversion function.
func Convert_v1_ExecCredential_To_clientauthentication_ExecCredential(in *ExecCredential, out *clientauthentication.ExecCredential, s conversion.Scope) error {
	return autoConvert_v1_ExecCredential_To_clientauthentication_ExecCredential(in, out, s)
}

func autoConvert_clientauthentication_ExecCredential_To_v1_ExecCredential(in *clientauthentication.ExecCredential, out *ExecCredential, s conversion.Scope) error {
	if err := Convert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*ExecCredentialStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_clientauthentication_ExecCredential_To_v1_ExecCredential is an autogenerated conversion function.
func Convert_clientauthentication_ExecCredential_To_v1_ExecCredential(in *clientauthentication.ExecCredential, out *ExecCredential, s conversion.Scope) error {
	return autoConvert_clientauthentication_ExecCredential_To_v1_ExecCredential(in, out, s)
}

func autoConvert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec(in *ExecCredentialSpec, out *clientauthentication.ExecCredentialSpec, s conversion.Scope) error {
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(clientauthentication.Cluster)
		if err := Convert_v1_Cluster_To_clientauthentication_Cluster(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Cluster = nil
	}
	out.Interactive = in.Interactive
	out.HTTPSignature = (*clientauthentication.HTTPSignatureRequest)(unsafe.Pointer(in.HTTPSignature))
	return nil
}

// Convert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec is an autogenerated conversion function.
func Convert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec(in *ExecCredentialSpec, out *clientauthentication.ExecCredentialSpec, s conversion.Scope) error {
	return autoConvert_v1_ExecCredentialSpec_To_clientauthentication_ExecCredentialSpec(in, out, s)
}

func autoConvert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec(in *clientauthentication.ExecCredentialSpec, out *ExecCredentialSpec, s conversion.Scope) error {
	out.Interactive = in.Interactive
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(Cluster)
		if err := Convert_clientauthentication_Cluster_To_v1_Cluster(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Cluster = nil
	}
	out.HTTPSignature = (*HTTPSignatureRequest)(unsafe.Pointer(in.HTTPSignature))
	return nil
}

// Convert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec is an autogenerated conversion function.
func Convert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec(in *clientauthentication.ExecCredentialSpec, out *ExecCredentialSpec, s conversion.Scope) error {
	return autoConvert_clientauthentication_ExecCredentialSpec_To_v1_ExecCredentialSpec(in, out, s)
}

func autoConvert_v1_ExecCredentialStatus_To_clientauthentication_ExecCredentialStatus(in *ExecCredentialStatus, out *clientauthentication.ExecCredentialStatus, s conversion.Scope) error {
	*out = *(*clientauthentication.ExecCredentialStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ExecCredentialStatus_To_clientauthentication_ExecCredentialStatus is an autogenerated conversion function.
func Convert_v1_ExecCredentialStatus_To_clientauthentication_ExecCredentialStatus(in *ExecCredentialStatus, out *clientauthentication.ExecCredentialStatus, s conversion.Scope) error {
	return autoConvert_v1_ExecCredentialStatus_To_clientauthentication_ExecCredentialStatus(in, out, s)
}

func autoConvert_clientauthentication_ExecCredentialStatus_To_v1_ExecCredentialStatus(in *clientauthentication.ExecCredentialStatus, out *ExecCredentialStatus, s conversion.Scope) error {
	*out = *(*ExecCredentialStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_ExecCredentialStatus_To_v1_ExecCredentialStatus is an autogenerated conversion function.
func Convert_clientauthentication_ExecCredentialStatus_To_v1_ExecCredentialStatus(in *clientauthentication.ExecCredentialStatus, out *ExecCredentialStatus, s conversion.Scope) error {
	return autoConvert_clientauthentication_ExecCredentialStatus_To_v1_ExecCredentialStatus(in, out, s)
}

func autoConvert_v1_HTTPSignatureCredential_To_clientauthentication_HTTPSignatureCredential(in *HTTPSignatureCredential, out *clientauthentication.HTTPSignatureCredential, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureCredential)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureCredential_To_clientauthentication_HTTPSignatureCredential is an autogenerated conversion function.
func Convert_v1_HTTPSignatureCredential_To_clientauthentication_HTTPSignatureCredential(in *HTTPSignatureCredential, out *clientauthentication.HTTPSignatureCredential, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureCredential_To_clientauthentication_HTTPSignatureCredential(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureCredential_To_v1_HTTPSignatureCredential(in *clientauthentication.HTTPSignatureCredential, out *HTTPSignatureCredential, s conversion.Scope) error {
	*out = *(*HTTPSignatureCredential)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureCredential_To_v1_HTTPSignatureCredential is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureCredential_To_v1_HTTPSignatureCredential(in *clientauthentication.HTTPSignatureCredential, out *HTTPSignatureCredential, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureCredential_To_v1_HTTPSignatureCredential(in, out, s)
}

func autoConvert_v1_HTTPSignatureHeader_To_clientauthentication_HTTPSignatureHeader(in *HTTPSignatureHeader, out *clientauthentication.HTTPSignatureHeader, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureHeader)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureHeader_To_clientauthentication_HTTPSignatureHeader is an autogenerated conversion function.
func Convert_v1_HTTPSignatureHeader_To_clientauthentication_HTTPSignatureHeader(in *HTTPSignatureHeader, out *clientauthentication.HTTPSignatureHeader, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureHeader_To_clientauthentication_HTTPSignatureHeader(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureHeader_To_v1_HTTPSignatureHeader(in *clientauthentication.HTTPSignatureHeader, out *HTTPSignatureHeader, s conversion.Scope) error {
	*out = *(*HTTPSignatureHeader)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureHeader_To_v1_HTTPSignatureHeader is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureHeader_To_v1_HTTPSignatureHeader(in *clientauthentication.HTTPSignatureHeader, out *HTTPSignatureHeader, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureHeader_To_v1_HTTPSignatureHeader(in, out, s)
}

func autoConvert_v1_HTTPSignatureKeyDerivation_To_clientauthentication_HTTPSignatureKeyDerivation(in *HTTPSignatureKeyDerivation, out *clientauthentication.HTTPSignatureKeyDerivation, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureKeyDerivation)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureKeyDerivation_To_clientauthentication_HTTPSignatureKeyDerivation is an autogenerated conversion function.
func Convert_v1_HTTPSignatureKeyDerivation_To_clientauthentication_HTTPSignatureKeyDerivation(in *HTTPSignatureKeyDerivation, out *clientauthentication.HTTPSignatureKeyDerivation, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureKeyDerivation_To_clientauthentication_HTTPSignatureKeyDerivation(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureKeyDerivation_To_v1_HTTPSignatureKeyDerivation(in *clientauthentication.HTTPSignatureKeyDerivation, out *HTTPSignatureKeyDerivation, s conversion.Scope) error {
	*out = *(*HTTPSignatureKeyDerivation)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureKeyDerivation_To_v1_HTTPSignatureKeyDerivation is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureKeyDerivation_To_v1_HTTPSignatureKeyDerivation(in *clientauthentication.HTTPSignatureKeyDerivation, out *HTTPSignatureKeyDerivation, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureKeyDerivation_To_v1_HTTPSignatureKeyDerivation(in, out, s)
}

func autoConvert_v1_HTTPSignatureKeyDerivationStep_To_clientauthentication_HTTPSignatureKeyDerivationStep(in *HTTPSignatureKeyDerivationStep, out *clientauthentication.HTTPSignatureKeyDerivationStep, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureKeyDerivationStep)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureKeyDerivationStep_To_clientauthentication_HTTPSignatureKeyDerivationStep is an autogenerated conversion function.
func Convert_v1_HTTPSignatureKeyDerivationStep_To_clientauthentication_HTTPSignatureKeyDerivationStep(in *HTTPSignatureKeyDerivationStep, out *clientauthentication.HTTPSignatureKeyDerivationStep, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureKeyDerivationStep_To_clientauthentication_HTTPSignatureKeyDerivationStep(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureKeyDerivationStep_To_v1_HTTPSignatureKeyDerivationStep(in *clientauthentication.HTTPSignatureKeyDerivationStep, out *HTTPSignatureKeyDerivationStep, s conversion.Scope) error {
	*out = *(*HTTPSignatureKeyDerivationStep)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureKeyDerivationStep_To_v1_HTTPSignatureKeyDerivationStep is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureKeyDerivationStep_To_v1_HTTPSignatureKeyDerivationStep(in *clientauthentication.HTTPSignatureKeyDerivationStep, out *HTTPSignatureKeyDerivationStep, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureKeyDerivationStep_To_v1_HTTPSignatureKeyDerivationStep(in, out, s)
}

func autoConvert_v1_HTTPSignatureRequest_To_clientauthentication_HTTPSignatureRequest(in *HTTPSignatureRequest, out *clientauthentication.HTTPSignatureRequest, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureRequest)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureRequest_To_clientauthentication_HTTPSignatureRequest is an autogenerated conversion function.
func Convert_v1_HTTPSignatureRequest_To_clientauthentication_HTTPSignatureRequest(in *HTTPSignatureRequest, out *clientauthentication.HTTPSignatureRequest, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureRequest_To_clientauthentication_HTTPSignatureRequest(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureRequest_To_v1_HTTPSignatureRequest(in *clientauthentication.HTTPSignatureRequest, out *HTTPSignatureRequest, s conversion.Scope) error {
	*out = *(*HTTPSignatureRequest)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureRequest_To_v1_HTTPSignatureRequest is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureRequest_To_v1_HTTPSignatureRequest(in *clientauthentication.HTTPSignatureRequest, out *HTTPSignatureRequest, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureRequest_To_v1_HTTPSignatureRequest(in, out, s)
}

func autoConvert_v1_HTTPSignatureStage_To_clientauthentication_HTTPSignatureStage(in *HTTPSignatureStage, out *clientauthentication.HTTPSignatureStage, s conversion.Scope) error {
	*out = *(*clientauthentication.HTTPSignatureStage)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_HTTPSignatureStage_To_clientauthentication_HTTPSignatureStage is an autogenerated conversion function.
func Convert_v1_HTTPSignatureStage_To_clientauthentication_HTTPSignatureStage(in *HTTPSignatureStage, out *clientauthentication.HTTPSignatureStage, s conversion.Scope) error {
	return autoConvert_v1_HTTPSignatureStage_To_clientauthentication_HTTPSignatureStage(in, out, s)
}

func autoConvert_clientauthentication_HTTPSignatureStage_To_v1_HTTPSignatureStage(in *clientauthentication.HTTPSignatureStage, out *HTTPSignatureStage, s conversion.Scope) error {
	*out = *(*HTTPSignatureStage)(unsafe.Pointer(in))
	return nil
}

// Convert_clientauthentication_HTTPSignatureStage_To_v1_HTTPSignatureStage is an autogenerated conversion function.
func Convert_clientauthentication_HTTPSignatureStage_To_v1_HTTPSignatureStage(in *clientauthentication.HTTPSignatureStage, out *HTTPSignatureStage, s conversion.Scope) error {
	return autoConvert_clientauthentication_HTTPSignatureStage_To_v1_HTTPSignatureStage(in, out, s)
}
